# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

resources:
- repo: self

trigger:
  - master
  - development
  - release/*
  - feature/*
  - hotfix/*

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: 'MedicalExaminer.API/MedicalExaminer.API.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: 'MedicalExaminer.API/MedicalExaminer.API.csproj'
    arguments: '--configuration $(BuildConfiguration)'


- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    codeCoverageEnabled: True
    command: test
    projects: 'MedicalExaminer.API.Tests/MedicalExaminer.API.Tests.csproj'
    arguments: '--configuration $(BuildConfiguration)'
    publishTestResults: true

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'MedicalExaminer.API/MedicalExaminer.API.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
      
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

