version: '3.4'

services:
  medicalexaminerapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
#      - ASPNETCORE_HTTPS_PORT=44371
    ports:
      - "9000:80"
 #     - "44371:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro